substitutions:
  flowmeterpin: "14"
  update_flowmeter: "5s"


sensor:
  - platform: pulse_counter
    id: flowmeter
    name: 'Flow Meter'
    device_class: 'volume'
    unit_of_measurement: 'ml/min'
    accuracy_decimals: 2
    pin: 
        number: ${flowmeterpin}
        mode:
          input: true
          pullup: true
    update_interval: ${update_flowmeter}
    filters:
    - lambda: return (x / 5.160);  
    
    total:
      unit_of_measurement: 'ml'
      name: 'Flow Meter Total'
      accuracy_decimals: 2
      device_class: 'volume'
      filters:
      - lambda: return (x /  5.160);
