substitutions:
  tdspin1: "35"
  update_tds: "8s"

sensor:
  - platform: adc
    pin: ${tdspin1}
    name: "TDS"
    id : "tds"
    update_interval: ${update_tds}
    unit_of_measurement: "ppm"
    filters:
      - lambda: return (((133.42*(x*(3.3/1024))*(x*(3.3/1024))*(x*(3.3/1024))) - (255.86*(x*(3.3/1024))*(x*(3.3/1024))) + (857.39*(x*(3.3/1024))))*0.5)*1000;
      # - lambda: return (133.42*(id(temp01_comp_v).state)*(id(temp01_comp_v).state)*(id(temp01_comp_v).state) - 255.86*(id(temp01_comp_v).state)*(id(temp01_comp_v).state) + 857.39*(id(temp01_comp_v).state))*0.5;
