substitutions:
  tdspin1: "35"
  update_tds: "8s"

sensor:
  - platform: adc
    pin: ${tdspin1}
    name: "TDS"
    id : "tds"
    update_interval: ${update_tds}
    unit_of_measurement: "ppm"
    filters:
      - lambda: return (133.42*x*x*x - 255.86*x*x + 857.39*x)*0.5;
