substitutions:
  tdspin1: "35"
  update_tds: "5s"
  # tds_temp : "28"

sensor:
  - platform: custom
    lambda: |-
      auto tds_sensor = new TdsSensor(28.0,${tdspin1});
      App.register_component(tds_sensor);
      return {tds_sensor->tds_sensor, tds_sensor->voltage_sensor};
    sensors:
      - name: "Water TDS"
        unit_of_measurement: ppm
        accuracy_decimals: 2
      - name: "Water Voltage"
        unit_of_measurement: mV
        accuracy_decimals: 0